[tool.portray]
docs_dir="documentation\\markdown"
modules=[
    "easyagents.agents",
    "easyagents.agents",
    "easyagents.core",
    "easyagents.backends.core",
    "easyagents.backends.tfagents",
    "easyagents.callbacks.duration",
    "easyagents.callbacks.log",
    "easyagents.callbacks.plot",
    "easyagents.callbacks.save",
    ]




